# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/clubmanager_db
spring.datasource.username=postgres
spring.datasource.password=SQLtopg

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# App
spring.application.name=clubmanager

# JWT (baad mein use hoga, abhi set kar lo)
app.jwt.secret=thisIsAVeryLongSecretKeyForJWTThatShouldBeAtLeast256BitsLongForSecurity
app.jwt.expiration=86400000